// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MicrowaveCommander.Infrastructure.Data;

#nullable disable

namespace MicrowaveCommander.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicrowaveCommander.Domain.Entities.Programs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Meal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProgramsDbSet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instructions = "Observar o barulho de estouros do milho, caso houver um intervalo de mais de 10 segundos entre um estouro e outro, interrompa o aquecimento.",
                            IsCustom = false,
                            Meal = "Pipoca (de micro-ondas)",
                            Name = "Pipoca",
                            Power = 7,
                            ProcessingString = "p",
                            TimeInMinutes = 3,
                            TimeInSeconds = 183
                        },
                        new
                        {
                            Id = 2,
                            Instructions = "Cuidado com aquecimento de líquidos, o choque térmico aliado ao movimento do recipiente pode causar fervura imediata causando risco de queimaduras.",
                            IsCustom = false,
                            Meal = "Leite",
                            Name = "Leite",
                            Power = 5,
                            ProcessingString = "l",
                            TimeInMinutes = 5,
                            TimeInSeconds = 300
                        },
                        new
                        {
                            Id = 3,
                            Instructions = "Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            IsCustom = false,
                            Meal = "Carne em pedaço ou fatias",
                            Name = "Carnes de boi",
                            Power = 4,
                            ProcessingString = "c",
                            TimeInMinutes = 14,
                            TimeInSeconds = 840
                        },
                        new
                        {
                            Id = 4,
                            Instructions = "Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            IsCustom = false,
                            Meal = "Frango (qualquer corte)",
                            Name = "Frango",
                            Power = 7,
                            ProcessingString = "f",
                            TimeInMinutes = 8,
                            TimeInSeconds = 480
                        },
                        new
                        {
                            Id = 5,
                            Instructions = "Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            IsCustom = false,
                            Meal = "Feijão congelado",
                            Name = "Feijão",
                            Power = 9,
                            ProcessingString = "j",
                            TimeInMinutes = 8,
                            TimeInSeconds = 480
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
